In [8]:
import numpy as np

A = np.matrix([[10,95,8],[95,20,9],[8,9,30]])
B = np.matrix([[5,8,3,6],[95,20,9,3],[8,9,30,3],[8,9,30,3]])
C = np.matrix([[0,6,250],[-6,0,86.3],[-250,-86.3,0]])

print("Transpose of A is:",np.transpose(A),sep="\n")
print("Transpose of B is:",np.transpose(B),sep="\n")
print("Transpose of C is:",np.transpose(C),sep="\n")

print("Inverse of A is:",np.linalg.inv(A),sep="\n")
#print("Inverse of B is:",np.linalg.inv(B),sep="\n")
#print("Inverse of C is:",np.linalg.inv(C),sep="\n")

#print("Determinant of A is:",np.linalg.det(A),sep="\n")
#print("Determinant of B is:",np.linalg.det(B),sep="\n")
#print("Determinant of C is:",np.linalg.det(C),sep="\n")

print(np.allclose(A,np.transpose(A)))
print("A is a symmetric matrix")

print("B is a singular matrix")
print("C is a singular matrix")

#print("Addition of A and B is:",A+B,sep="\n")
print("Addition of A and B is not possible as both matrices have different dimensions")

#print("Multiplication of A and B is:",np.matmul(A,B),sep="\n")
print("Multiplication of A and B is not possible because number of columns of matrix A is not equal to the number of rows of matrix B")

Transpose of A is:
[[10 95  8]
 [95 20  9]
 [ 8  9 30]]
Transpose of B is:
[[ 5 95  8  8]
 [ 8 20  9  9]
 [ 3  9 30 30]
 [ 6  3  3  3]]
Transpose of C is:
[[   0.    -6.  -250. ]
 [   6.     0.   -86.3]
 [ 250.    86.3    0. ]]
Inverse of A is:
[[-0.00205009  0.0109733  -0.0027453 ]
 [ 0.0109733  -0.00093222 -0.00264655]
 [-0.0027453  -0.00264655  0.03485938]]
True
A is a symmetric matrix
B is a singular matrix
C is a singular matrix
Addition of A and B is not possible as both matrices have different dimensions
Multiplication of A and B is not possible because number of columns of matrix A is not equal to the number of rows of matrix B


In [14]:
def check_matrices(mat):
    mat_T=np.transpose(mat)
    sym_check=np.allclose(mat_T,mat)
    sksym_check=np.allclose(mat_T,-mat)
    singular_check=np.linalg.det(mat)
    results={"symmetric":sym_check,
            "skew_symmetric":sksym_check,
            "singular_matric":singular_check}
    return results
results_A=check_matrices(A)
results_B=check_matrices(B)
results_C=check_matrices(C)

print("Result from check matrices for A:\n {}".format(results_A))
print("Result from check matrices for A:\n {}".format(results_B))
print("Result from check matrices for A:\n {}".format(results_C))

singular_A ="non-singular"
singular_B="singular"
singular_C="singular"
print("A is {},B is {},C is {}".format(singular_A,singular_B,singular_C))


Result from check matrices for A:
 {'symmetric': True, 'skew_symmetric': False, 'singular_matric': -253159.99999999977}
Result from check matrices for A:
 {'symmetric': False, 'skew_symmetric': False, 'singular_matric': 0.0}
Result from check matrices for A:
 {'symmetric': False, 'skew_symmetric': True, 'singular_matric': 6.827871601444718e-12}
A is non-singular,B is singular,C is singular
