In [2]:
import numpy as np

A = np.matrix([[10,95,8],[95,20,9],[8,9,30]])
B = np.matrix([[5,8,3,6],[95,20,9,3],[8,9,30,3],[8,9,30,3]])
C = np.matrix([[0,6,250],[-6,0,86.3],[-250,-86.3,0]])

print("Transpose of A is:",np.transpose(A),sep="\n")
print("Transpose of B is:",np.transpose(B),sep="\n")
print("Transpose of C is:",np.transpose(C),sep="\n")

print("Inverse of A is:",np.linalg.inv(A),sep="\n")
#print("Inverse of B is:",np.linalg.inv(B),sep="\n")
#print("Inverse of C is:",np.linalg.inv(C),sep="\n")

#print("Determinant of A is:",np.linalg.det(A),sep="\n")
#print("Determinant of B is:",np.linalg.det(B),sep="\n")
#print("Determinant of C is:",np.linalg.det(C),sep="\n")

print(np.allclose(A,np.transpose(A)))
print("A is a symmetric matrix")

print("B is a singular matrix")
print("C is a singular matrix")

#print("Addition of A and B is:",A+B,sep="\n")
print("Addition of A and B is not possible as both matrices have different dimensions")

#print("Multiplication of A and B is:",np.matmul(A,B),sep="\n")
print("Multiplication of A and B is not possible because number of columns of matrix A is not equal to the number of rows of matrix B")

Transpose of A is:
[[10 95  8]
 [95 20  9]
 [ 8  9 30]]
Transpose of B is:
[[ 5 95  8  8]
 [ 8 20  9  9]
 [ 3  9 30 30]
 [ 6  3  3  3]]
Transpose of C is:
[[   0.    -6.  -250. ]
 [   6.     0.   -86.3]
 [ 250.    86.3    0. ]]
Inverse of A is:
[[-0.00205009  0.0109733  -0.0027453 ]
 [ 0.0109733  -0.00093222 -0.00264655]
 [-0.0027453  -0.00264655  0.03485938]]
True
A is a symmetric matrix
B is a singular matrix
C is a singular matrix
Addition of A and B is not possible as both matrices have different dimensions
Multiplication of A and B is not possible because number of columns of matrix A is not equal to the number of rows of matrix B
