In [1]:
import numpy as np
a=-10
np.abs(a)

def abs(x):
    if x<0:
        x=-x
        return x
print(abs(-12))

12


In [2]:
#adding more code letter that I forgot about earlier today

In [3]:
import numpy as np
A=np.array([[3,-9],[2,4]])
print (A)

[[ 3 -9]
 [ 2  4]]


In [4]:
b=np.array([-42,2])

In [5]:
z=np.linalg.solve(A,b)
print(z)

[-5.  3.]


In [6]:
A=np.array([[1,-2,-1],[2,2,-1],[1,1,-2]])
b=([6,1,-1])
z=np.linalg.solve(A,b)
print(z)

[ 3. -2.  1.]


In [7]:
A=np.array([[1,1,2],[3,5,8]])
B=np.array([[2,3,5],[7,11,13]])
C=np.array([[3,1,4],[1,5,9],[2,6,5],[3,5,6]])
print(A + B)
print(A-B)
print(100*C)

[[ 3  4  7]
 [10 16 21]]
[[-1 -2 -3]
 [-4 -6 -5]]
[[300 100 400]
 [100 500 900]
 [200 600 500]
 [300 500 600]]


In [8]:
import numpy as np
A=np.array([3,4])
magnitude = np.linalg.norm(A,1)
print("magnitude of point P is {}".format(magnitude))

magnitude of point P is 7.0


In [9]:
a = {"Apples","Bananas","Peaches","Grapes","Bananas","Mangoes","Bananas"}
print(a)
print(type(a))
#a[0]
for x in a:
    print(x)
x

{'Apples', 'Peaches', 'Grapes', 'Mangoes', 'Bananas'}
<class 'set'>
Apples
Peaches
Grapes
Mangoes
Bananas


'Bananas'

In [10]:
𝐴={1,2,3,4,5,6,7,8,9,0} 
𝐵={2,4,6,8}
print(type(A))
print(type(B))
B.issubset(A)
A.issuperset(B)

<class 'set'>
<class 'set'>


True

In [14]:
my_set = {4,5}
print(my_set)
my_set.add(10)
print(my_set)
my_set.discard(5)
print(my_set)

{4, 5}
{10, 4, 5}
{10, 4}


In [15]:
!python --version

Python 3.7.3


In [29]:
A = {"Apples","Bananas","Mangoes"} 
B = {"Bananas","Tomatoes","Apples","Potatoes"}

# union 
print("Union:", A | B)
print("Union:", B | A)
#intersection
print("Intersection:",A & B)
print("Intersection:",B & A)
#difference A-B
print("Difference:",A-B)
print("Difference:",B-A)
#difference B-A
print("Addition:",B-A)
print("Addition:",B-A)
#symmetric difference
print("Symmetric difference:",A^B)
print("Symmetric difference:",B^A)

Union: {'Apples', 'Bananas', 'Potatoes', 'Mangoes', 'Tomatoes'}
Union: {'Apples', 'Bananas', 'Potatoes', 'Mangoes', 'Tomatoes'}
Intersection: {'Apples', 'Bananas'}
Intersection: {'Apples', 'Bananas'}
Difference: {'Mangoes'}
Difference: {'Potatoes', 'Tomatoes'}
Addition: {'Potatoes', 'Tomatoes'}
Addition: {'Potatoes', 'Tomatoes'}
Symmetric difference: {'Mangoes', 'Potatoes', 'Tomatoes'}
Symmetric difference: {'Potatoes', 'Mangoes', 'Tomatoes'}
