In [1]:
import numpy as np
a=-10
np.abs(a)

def abs(x):
    if x<0:
        x=-x
        return x
print(abs(-12))

12


In [ ]:
#adding more code letter that I forgot about earlier today

In [5]:
import numpy as np
A=np.array([[3,-9],[2,4]])
print (A)

[[ 3 -9]
 [ 2  4]]


In [6]:
b=np.array([-42,2])

In [7]:
z=np.linalg.solve(A,b)
print(z)

[-5.  3.]


In [9]:
A=np.array([[1,-2,-1],[2,2,-1],[1,1,-2]])
b=([6,1,-1])
z=np.linalg.solve(A,b)
print(z)

[ 3. -2.  1.]


In [19]:
A=np.array([[1,1,2],[3,5,8]])
B=np.array([[2,3,5],[7,11,13]])
C=np.array([[3,1,4],[1,5,9],[2,6,5],[3,5,6]])
print(A + B)
print(A-B)
print(100*C)

[[ 3  4  7]
 [10 16 21]]
[[-1 -2 -3]
 [-4 -6 -5]]
[[300 100 400]
 [100 500 900]
 [200 600 500]
 [300 500 600]]
